baseurl: /
permalink: /:title/
paginate: 4
paginate_path: "/blog/:num/"
markdown: rdiscount
relative_permalinks: false
excerpt_separator: <!--more-->
exclude: ["README.md","Gemfile","Gemfile.lock","CNAME","gruntfile.js","package.json","node_modules","js/layout","js/components","js/production.js"]

sass:
  sass_dir: _sass
  style: :compressed
